/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.admin;

import Model.Program;
import DataStore.DataStore;

/**
 *
 * @author arelssi
 */
public class FormTambahProgram extends javax.swing.JFrame {

    private Views.admin.PanelDataProgram panelInduk; 

    // UBAH CONSTRUCTOR MENJADI SEPERTI INI:
    public FormTambahProgram(Views.admin.PanelDataProgram panelInduk) {
        initComponents();
        this.setLocationRelativeTo(null); // Biar pop-up muncul pas di tengah layar
        
        this.panelInduk = panelInduk;
        
        siapkanForm();
    }
    
    private void siapkanForm() {
        int jumlahProgram = DataStore.daftarProgram.size() + 1;
        
        String idBaru = String.format("PRG%03d", jumlahProgram); 
        
        txtIdProgram.setText(idBaru);
        txtIdProgram.setEditable(false);
        
        cbBidangUsaha.removeAllItems();
        cbBidangUsaha.addItem("Pabrik / Perakitan");
        cbBidangUsaha.addItem("Kesehatan / Lansia");
        cbBidangUsaha.addItem("Agrikultur");
        cbBidangUsaha.addItem("Konstruksi");
        cbBidangUsaha.addItem("Lainnya...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelBody = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtIdProgram = new javax.swing.JTextField();
        txtNamaProgram = new javax.swing.JTextField();
        cbBidangUsaha = new javax.swing.JComboBox<>();
        txtBiaya = new javax.swing.JSpinner();
        txtKuota = new javax.swing.JSpinner();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(122, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(560, 68));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/videocall (1).png")); // NOI18N
        jLabel1.setText("Icon");
        jLabel1.setPreferredSize(new java.awt.Dimension(36, 36));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 18, -1, -1));

        jLabel2.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tambah Program Baru");
        jLabel2.setPreferredSize(new java.awt.Dimension(280, 22));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 14, -1, -1));

        jLabel3.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 200, 200));
        jLabel3.setText("Isi seluruh data program dengan benar");
        jLabel3.setPreferredSize(new java.awt.Dimension(300, 16));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 38, -1, -1));

        jButton1.setBackground(new java.awt.Color(160, 20, 20));
        jButton1.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 18, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelBody.setBackground(new java.awt.Color(255, 255, 255));
        panelBody.setPreferredSize(new java.awt.Dimension(560, 470));
        panelBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(122, 0, 0));
        jLabel4.setText("DATA PRIBADI");
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 14));
        panelBody.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, -1, -1));

        jSeparator1.setPreferredSize(new java.awt.Dimension(520, 8));
        panelBody.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 32, -1, -1));

        jLabel5.setText("ID Program");
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 14));
        panelBody.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 44, -1, -1));

        jLabel6.setText("Kuota");
        jLabel6.setPreferredSize(new java.awt.Dimension(120, 14));
        panelBody.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 44, -1, -1));

        jLabel7.setText("Nama Program");
        jLabel7.setPreferredSize(new java.awt.Dimension(200, 14));
        panelBody.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 102, -1, -1));

        jLabel9.setText("Bidang Usaha");
        jLabel9.setPreferredSize(new java.awt.Dimension(160, 14));
        panelBody.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jLabel11.setText("Biaya");
        panelBody.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 155, -1, -1));

        txtIdProgram.setEditable(false);
        txtIdProgram.setBackground(new java.awt.Color(245, 245, 245));
        txtIdProgram.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        txtIdProgram.setForeground(new java.awt.Color(160, 160, 160));
        txtIdProgram.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 210, 210)));
        txtIdProgram.setPreferredSize(new java.awt.Dimension(240, 34));
        panelBody.add(txtIdProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtNamaProgram.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        txtNamaProgram.setForeground(new java.awt.Color(60, 60, 60));
        txtNamaProgram.setPreferredSize(new java.awt.Dimension(520, 34));
        panelBody.add(txtNamaProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 118, -1, -1));

        cbBidangUsaha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbBidangUsaha.setPreferredSize(new java.awt.Dimension(250, 34));
        panelBody.add(cbBidangUsaha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 176, -1, -1));
        panelBody.add(txtBiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 240, 30));

        txtKuota.setPreferredSize(new java.awt.Dimension(64, 33));
        panelBody.add(txtKuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 250, -1));

        getContentPane().add(panelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, -1, 250));

        btnBatal.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(80, 80, 80));
        btnBatal.setText("Batal");
        btnBatal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 210, 210)));
        btnBatal.setPreferredSize(new java.awt.Dimension(100, 34));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        btnSimpan.setBackground(new java.awt.Color(122, 0, 0));
        btnSimpan.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorderPainted(false);
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.setFocusPainted(false);
        btnSimpan.setPreferredSize(new java.awt.Dimension(118, 34));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        int konfirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Data yang diisi akan hilang. Yakin ingin membatalkan?",
            "Konfirmasi Batal",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
        if (konfirm == javax.swing.JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // 1. Ambil data dari semua inputan
        String idProgram = txtIdProgram.getText();
        String namaProgram = txtNamaProgram.getText().trim();
        String bidangUsaha = cbBidangUsaha.getSelectedItem().toString();
        
        if (namaProgram.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Nama Program tidak boleh kosong!", "Peringatan", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int biaya = 0;
        int kuota = 0;
        try {
            // Jika kamu pakai JSpinner, gunakan .getValue(). Jika JTextField, gunakan .getText()
            // Di sini saya asumsikan kamu pakai JSpinner (karena ada panah atas bawah di screenshot)
            biaya = (Integer) txtKuota.getValue();
            kuota = (Integer) txtKuota.getValue();
            
            if (biaya < 0 || kuota <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Biaya tidak boleh minus dan Kuota harus lebih dari 0!", "Peringatan", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Input Biaya dan Kuota harus berupa angka yang valid!", "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Program programBaru = new Program(idProgram, namaProgram, bidangUsaha, biaya, kuota);
        DataStore.daftarProgram.add(programBaru);
        
        if (panelInduk != null) {
            panelInduk.loadTableData("");
        }
        
        javax.swing.JOptionPane.showMessageDialog(this, "Program Baru Berhasil Ditambahkan!");
        this.dispose();
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbBidangUsaha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelBody;
    private javax.swing.JSpinner txtBiaya;
    private javax.swing.JTextField txtIdProgram;
    private javax.swing.JSpinner txtKuota;
    private javax.swing.JTextField txtNamaProgram;
    // End of variables declaration//GEN-END:variables
}
