/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author arelssi
 */
public class AdminFrame extends javax.swing.JFrame {
    private void showPanel(JPanel panel) {
            mainContent.removeAll(); 

            mainContent.setLayout(new java.awt.BorderLayout());
            mainContent.add(panel, java.awt.BorderLayout.CENTER);

            mainContent.repaint();
            mainContent.revalidate();
        }

        private Color colorActive = new Color(90, 0, 0);
        private Color colorDefault = new Color(122, 0, 0);
        private Color foregroundActive = new Color(255,255,255);
        private Color foregroundDefault = new Color(255,210,210);

        private void setActiveButton(JButton activeBtn) {
        JButton[] sidebarButtons = {btnDashboard, btnPeserta, btnInstruktur, btnProgram, btnManajemenSeleksi};

        for (JButton btn : sidebarButtons) {
            btn.setBackground(colorDefault);
            btn.setForeground(foregroundDefault);
            btn.setOpaque(true);
            btn.setBorderPainted(false);
        }

            activeBtn.setBackground(colorActive);
            activeBtn.setForeground(foregroundActive);
        }


    public AdminFrame() {
        initComponents();
        setSize(1200, 680);
            pack();
            setLocationRelativeTo(null);
            setResizable(false);
            setTitle("LPK Yuuki - Dashboard Admin");
            setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

            lblTanggal.setText(new java.text.SimpleDateFormat("EEEE, dd MMMM yyyy", 
                               new java.util.Locale("id", "ID")).format(new java.util.Date()));
            showPanel(new PanelAdmin());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnInstruktur = new javax.swing.JButton();
        btnPeserta = new javax.swing.JButton();
        btnProgram = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        btnManajemenSeleksi = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jButton8 = new javax.swing.JButton();
        panelHeadr = new javax.swing.JPanel();
        lblHalamanJudul = new javax.swing.JLabel();
        lblHalamanSub = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mainContent = new javax.swing.JPanel();
        panelKartu1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblTotalPeserta = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelKartu2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblPesertaLulus = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        panelKartu3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        lblPesertaGugur = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        panelkartu4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblTotalInstruktur = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPeserta = new javax.swing.JTable();
        btnTambahPeserta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebar.setBackground(new java.awt.Color(122, 0, 0));
        sidebar.setName("panelSidebar"); // NOI18N
        sidebar.setPreferredSize(new java.awt.Dimension(220, 680));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("JetBrainsMono NF ExtraBold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LPK YUUKI");
        jLabel1.setPreferredSize(new java.awt.Dimension(180, 26));
        sidebar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 24, -1, -1));

        jLabel2.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 180, 180));
        jLabel2.setText("Training Center Indonesia");
        jLabel2.setPreferredSize(new java.awt.Dimension(180, 16));
        sidebar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 52, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(160, 30, 30));
        jSeparator1.setPreferredSize(new java.awt.Dimension(220, 16));
        sidebar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 130, 20));

        jLabel3.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 160, 160));
        jLabel3.setText("MENU UTAMA");
        jLabel3.setPreferredSize(new java.awt.Dimension(160, 14));
        sidebar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 96, -1, -1));

        btnDashboard.setBackground(new java.awt.Color(122, 0, 0));
        btnDashboard.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 210, 210));
        btnDashboard.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/home.png")); // NOI18N
        btnDashboard.setText(" Dashboard");
        btnDashboard.setBorderPainted(false);
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.setFocusPainted(false);
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard.setPreferredSize(new java.awt.Dimension(220, 42));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        sidebar.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 116, -1, -1));

        btnInstruktur.setBackground(new java.awt.Color(122, 0, 0));
        btnInstruktur.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        btnInstruktur.setForeground(new java.awt.Color(255, 210, 210));
        btnInstruktur.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/teacher.png")); // NOI18N
        btnInstruktur.setText(" Data Instruktur");
        btnInstruktur.setBorderPainted(false);
        btnInstruktur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInstruktur.setFocusPainted(false);
        btnInstruktur.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInstruktur.setPreferredSize(new java.awt.Dimension(220, 42));
        btnInstruktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstrukturActionPerformed(evt);
            }
        });
        sidebar.add(btnInstruktur, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        btnPeserta.setBackground(new java.awt.Color(122, 0, 0));
        btnPeserta.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        btnPeserta.setForeground(new java.awt.Color(255, 210, 210));
        btnPeserta.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/group (2).png")); // NOI18N
        btnPeserta.setText(" Data Peserta");
        btnPeserta.setBorderPainted(false);
        btnPeserta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPeserta.setFocusPainted(false);
        btnPeserta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPeserta.setPreferredSize(new java.awt.Dimension(220, 42));
        btnPeserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesertaActionPerformed(evt);
            }
        });
        sidebar.add(btnPeserta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 158, -1, -1));

        btnProgram.setBackground(new java.awt.Color(122, 0, 0));
        btnProgram.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        btnProgram.setForeground(new java.awt.Color(255, 210, 210));
        btnProgram.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/briefcase (1).png")); // NOI18N
        btnProgram.setText(" Data Program");
        btnProgram.setBorderPainted(false);
        btnProgram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProgram.setFocusPainted(false);
        btnProgram.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProgram.setPreferredSize(new java.awt.Dimension(220, 42));
        btnProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProgramActionPerformed(evt);
            }
        });
        sidebar.add(btnProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 242, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(160, 30, 30));
        jSeparator2.setPreferredSize(new java.awt.Dimension(220, 8));
        sidebar.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 150, 20));

        jLabel4.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 160, 160));
        jLabel4.setText("SELEKSI & KEBERANGKATAN");
        sidebar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 304, -1, -1));

        btnManajemenSeleksi.setBackground(new java.awt.Color(122, 0, 0));
        btnManajemenSeleksi.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        btnManajemenSeleksi.setForeground(new java.awt.Color(255, 210, 210));
        btnManajemenSeleksi.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/approval.png")); // NOI18N
        btnManajemenSeleksi.setText(" Manajemen Seleksi");
        btnManajemenSeleksi.setBorderPainted(false);
        btnManajemenSeleksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManajemenSeleksi.setFocusPainted(false);
        btnManajemenSeleksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnManajemenSeleksi.setPreferredSize(new java.awt.Dimension(220, 42));
        btnManajemenSeleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManajemenSeleksiActionPerformed(evt);
            }
        });
        sidebar.add(btnManajemenSeleksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 324, -1, -1));

        jButton6.setBackground(new java.awt.Color(122, 0, 0));
        jButton6.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 210, 210));
        jButton6.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/google-docs.png")); // NOI18N
        jButton6.setText(" Dokumen & Berangkat");
        jButton6.setBorderPainted(false);
        jButton6.setFocusPainted(false);
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setPreferredSize(new java.awt.Dimension(220, 42));
        sidebar.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 366, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(160, 30, 30));
        jSeparator3.setPreferredSize(new java.awt.Dimension(220, 8));
        sidebar.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 414, 120, 20));

        jLabel5.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 160, 160));
        jLabel5.setText("LAPORAN");
        jLabel5.setPreferredSize(new java.awt.Dimension(160, 14));
        sidebar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 428, -1, -1));

        jButton7.setBackground(new java.awt.Color(122, 0, 0));
        jButton7.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 210, 210));
        jButton7.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/bar-chart (1).png")); // NOI18N
        jButton7.setText(" Lihat Laporan");
        jButton7.setBorderPainted(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusPainted(false);
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.setPreferredSize(new java.awt.Dimension(220, 41));
        sidebar.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 448, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 160, 160));
        jSeparator4.setPreferredSize(new java.awt.Dimension(220, 8));
        sidebar.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 120, 20));

        jButton8.setBackground(new java.awt.Color(100, 0, 0));
        jButton8.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 160, 160));
        jButton8.setText("Logout");
        jButton8.setBorderPainted(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setFocusPainted(false);
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.setPreferredSize(new java.awt.Dimension(220, 42));
        sidebar.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, -1, -1));

        panelHeadr.setBackground(new java.awt.Color(255, 255, 255));
        panelHeadr.setPreferredSize(new java.awt.Dimension(980, 64));
        panelHeadr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHalamanJudul.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        lblHalamanJudul.setForeground(new java.awt.Color(25, 25, 25));
        lblHalamanJudul.setText("Dashboard");
        lblHalamanJudul.setPreferredSize(new java.awt.Dimension(200, 24));
        panelHeadr.add(lblHalamanJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 10, -1, -1));

        lblHalamanSub.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        lblHalamanSub.setForeground(new java.awt.Color(140, 140, 140));
        lblHalamanSub.setText("Selamat datang, Admin LPK");
        lblHalamanSub.setPreferredSize(new java.awt.Dimension(280, 24));
        panelHeadr.add(lblHalamanSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 36, -1, -1));

        lblTanggal.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        lblTanggal.setForeground(new java.awt.Color(140, 140, 140));
        lblTanggal.setText("Selasa, 12 Mei 2026");
        lblTanggal.setPreferredSize(new java.awt.Dimension(240, 16));
        panelHeadr.add(lblTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(40, 40, 40));
        jLabel9.setText("Admin LPK");
        jLabel9.setPreferredSize(new java.awt.Dimension(160, 16));
        panelHeadr.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, -1, -1));

        jLabel10.setText("A");
        panelHeadr.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(906, 12, -1, -1));

        mainContent.setBackground(new java.awt.Color(245, 245, 245));
        mainContent.setName("mainContent"); // NOI18N
        mainContent.setPreferredSize(new java.awt.Dimension(980, 616));
        mainContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelKartu1.setBackground(new java.awt.Color(255, 255, 255));
        panelKartu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        panelKartu1.setPreferredSize(new java.awt.Dimension(210, 100));
        panelKartu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Inter", 0, 22)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/user-solid (1) (1).png")); // NOI18N
        jLabel13.setText("s");
        jLabel13.setPreferredSize(new java.awt.Dimension(36, 36));
        panelKartu1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 60, 60));

        jLabel14.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(130, 130, 130));
        jLabel14.setText("Total Peserta");
        jLabel14.setPreferredSize(new java.awt.Dimension(140, 16));
        panelKartu1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblTotalPeserta.setFont(new java.awt.Font("Inter", 1, 28)); // NOI18N
        lblTotalPeserta.setForeground(new java.awt.Color(122, 0, 0));
        lblTotalPeserta.setText("10");
        lblTotalPeserta.setPreferredSize(new java.awt.Dimension(100, 36));
        panelKartu1.add(lblTotalPeserta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel16.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(170, 170, 170));
        jLabel16.setText("Peserta Terdaftar");
        jLabel16.setPreferredSize(new java.awt.Dimension(140, 16));
        panelKartu1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        mainContent.add(panelKartu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 24, -1, -1));

        panelKartu2.setBackground(new java.awt.Color(255, 255, 255));
        panelKartu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        panelKartu2.setPreferredSize(new java.awt.Dimension(210, 100));
        panelKartu2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Inter", 0, 22)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/check-solid (1).png")); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.setPreferredSize(new java.awt.Dimension(36, 36));
        panelKartu2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(130, 130, 130));
        jLabel12.setText("Peserta Lulus");
        jLabel12.setPreferredSize(new java.awt.Dimension(140, 16));
        panelKartu2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblPesertaLulus.setFont(new java.awt.Font("Inter", 1, 28)); // NOI18N
        lblPesertaLulus.setForeground(new java.awt.Color(0, 140, 60));
        lblPesertaLulus.setText("3");
        lblPesertaLulus.setPreferredSize(new java.awt.Dimension(100, 36));
        panelKartu2.add(lblPesertaLulus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel18.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(170, 170, 170));
        jLabel18.setText("lulus seleksi");
        jLabel18.setPreferredSize(new java.awt.Dimension(140, 16));
        panelKartu2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        mainContent.add(panelKartu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 24, -1, -1));

        panelKartu3.setBackground(new java.awt.Color(255, 255, 255));
        panelKartu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        panelKartu3.setPreferredSize(new java.awt.Dimension(210, 100));
        panelKartu3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("X");
        jLabel19.setPreferredSize(new java.awt.Dimension(36, 36));
        panelKartu3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        lblPesertaGugur.setFont(new java.awt.Font("Inter", 1, 28)); // NOI18N
        lblPesertaGugur.setForeground(new java.awt.Color(200, 0, 0));
        lblPesertaGugur.setText("0");
        lblPesertaGugur.setPreferredSize(new java.awt.Dimension(100, 36));
        panelKartu3.add(lblPesertaGugur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel21.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(130, 130, 130));
        jLabel21.setText("Peserta Gugur");
        jLabel21.setPreferredSize(new java.awt.Dimension(140, 16));
        panelKartu3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel22.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(170, 170, 170));
        jLabel22.setText("gugur permanen");
        jLabel22.setPreferredSize(new java.awt.Dimension(140, 16));
        panelKartu3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        mainContent.add(panelKartu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 24, -1, -1));

        panelkartu4.setBackground(new java.awt.Color(255, 255, 255));
        panelkartu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        panelkartu4.setPreferredSize(new java.awt.Dimension(210, 100));
        panelkartu4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/profile (3) (1).png")); // NOI18N
        jLabel23.setText("J");
        jLabel23.setPreferredSize(new java.awt.Dimension(36, 36));
        panelkartu4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel24.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(130, 130, 130));
        jLabel24.setText("Total Instruktur");
        jLabel24.setPreferredSize(new java.awt.Dimension(140, 16));
        panelkartu4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblTotalInstruktur.setFont(new java.awt.Font("Inter", 1, 28)); // NOI18N
        lblTotalInstruktur.setForeground(new java.awt.Color(0, 100, 100));
        lblTotalInstruktur.setText("5");
        lblTotalInstruktur.setPreferredSize(new java.awt.Dimension(100, 36));
        panelkartu4.add(lblTotalInstruktur, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel26.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(170, 170, 170));
        jLabel26.setText("instruktur aktif");
        jLabel26.setPreferredSize(new java.awt.Dimension(140, 16));
        panelkartu4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        mainContent.add(panelkartu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 24, -1, -1));

        jLabel27.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(25, 25, 25));
        jLabel27.setText("Daftar Peserta Terbaru");
        jLabel27.setPreferredSize(new java.awt.Dimension(280, 20));
        mainContent.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 148, -1, -1));

        jLabel28.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(150, 150, 150));
        jLabel28.setText("Menampilkan seluruh peserta yang terdaftar");
        jLabel28.setPreferredSize(new java.awt.Dimension(360, 16));
        mainContent.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 170, -1, -1));

        tabelPeserta.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        tabelPeserta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "ID Peserta", "Nama Lengkap", "Level Bahasa", "Program", "Status Seleksi", "Status Bayar", "Status Keberangkatan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelPeserta.setGridColor(new java.awt.Color(235, 235, 235));
        tabelPeserta.setRowHeight(34);
        tabelPeserta.setSelectionBackground(new java.awt.Color(255, 230, 230));
        tabelPeserta.setSelectionForeground(new java.awt.Color(122, 0, 0));
        tabelPeserta.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(tabelPeserta);

        scrollPane1.add(jScrollPane1);

        mainContent.add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 196, -1, -1));

        btnTambahPeserta.setBackground(new java.awt.Color(122, 0, 0));
        btnTambahPeserta.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        btnTambahPeserta.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahPeserta.setText("Tambah Peserta");
        btnTambahPeserta.setBorderPainted(false);
        btnTambahPeserta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambahPeserta.setFocusPainted(false);
        btnTambahPeserta.setPreferredSize(new java.awt.Dimension(134, 32));
        btnTambahPeserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahPesertaActionPerformed(evt);
            }
        });
        mainContent.add(btnTambahPeserta, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 148, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelHeadr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mainContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(panelHeadr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(mainContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        lblHalamanJudul.setText("Dashboard");
        lblHalamanSub.setText("Selamat datang, Admin LPK");

        showPanel(new PanelAdmin());
        setActiveButton(btnDashboard);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnInstrukturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstrukturActionPerformed
        lblHalamanJudul.setText("Data Instruktur");
        lblHalamanSub.setText("Kelola seluruh data Instruktur");

        showPanel(new PanelDataInstruktur());
        setActiveButton(btnInstruktur);
    }//GEN-LAST:event_btnInstrukturActionPerformed

    private void btnPesertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesertaActionPerformed
        lblHalamanJudul.setText("Data Peserta");
        lblHalamanSub.setText("Kelola seluruh data peserta pemagangan");

        showPanel(new PanelDataPeserta());
        setActiveButton(btnPeserta);
    }//GEN-LAST:event_btnPesertaActionPerformed

    private void btnProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProgramActionPerformed
        lblHalamanJudul.setText("Data Program");
        lblHalamanSub.setText("Kelola Data Program");

        showPanel(new PanelDataProgram());
        setActiveButton(btnProgram);
    }//GEN-LAST:event_btnProgramActionPerformed

    private void btnTambahPesertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPesertaActionPerformed
        FormTambahPeserta form = new FormTambahPeserta(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_btnTambahPesertaActionPerformed

    private void btnManajemenSeleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManajemenSeleksiActionPerformed
        lblHalamanJudul.setText("Manajemen Seleksi");
        lblHalamanSub.setText("Kelola Manajemen Seleksi Peserta");

        showPanel(new panelManajemenSeleksi());
        setActiveButton(btnManajemenSeleksi);
    }//GEN-LAST:event_btnManajemenSeleksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnInstruktur;
    private javax.swing.JButton btnManajemenSeleksi;
    private javax.swing.JButton btnPeserta;
    private javax.swing.JButton btnProgram;
    private javax.swing.JButton btnTambahPeserta;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblHalamanJudul;
    private javax.swing.JLabel lblHalamanSub;
    private javax.swing.JLabel lblPesertaGugur;
    private javax.swing.JLabel lblPesertaLulus;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblTotalInstruktur;
    private javax.swing.JLabel lblTotalPeserta;
    private javax.swing.JPanel mainContent;
    private javax.swing.JPanel panelHeadr;
    private javax.swing.JPanel panelKartu1;
    private javax.swing.JPanel panelKartu2;
    private javax.swing.JPanel panelKartu3;
    private javax.swing.JPanel panelkartu4;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JPanel sidebar;
    private javax.swing.JTable tabelPeserta;
    // End of variables declaration//GEN-END:variables
}
