/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import com.formdev.flatlaf.ui.FlatDropShadowBorder;
import java.awt.Color;
import java.awt.Insets;
import javax.swing.JFrame;

/**
 *
 * @author arelssi
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        setSize(1100, 686);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Sistem Manajemen Pemagangan ke japan - SIMAPAN");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        pnlRight.putClientProperty("JComponent.arc", 25);

        pnlRight.setBorder(
            new FlatDropShadowBorder(
                Color.BLACK,
                new Insets(5,5,15,15),
                0.25f
            )
        );
        txtUsername.putClientProperty(
            "FlatLaf.style",
            "arc:25"
        );
        txtPassword.putClientProperty(
            "FlatLaf.style",
            "arc:25"
        );
        btnLogin.putClientProperty(
            "FlatLaf.style",
            "arc:25"
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeft = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        pnlIkon1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlIkon2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnlIkon3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        bgImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLeft.setBackground(new java.awt.Color(245, 245, 245));
        pnlLeft.setPreferredSize(new java.awt.Dimension(620, 680));
        pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("JetBrainsMono NF ExtraBold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(122, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/Yuki-Logo-3-1024x389 (2).png")); // NOI18N
        jLabel1.setText(" LPK");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 40));
        pnlLeft.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 170, -1));

        jLabel2.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel2.setText("KERJA");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 20));
        pnlLeft.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 60, -1));

        jLabel3.setFont(new java.awt.Font("Inter", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 30, 30));
        jLabel3.setText("Sistem Manajemen");
        jLabel3.setPreferredSize(new java.awt.Dimension(400, 50));
        pnlLeft.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Inter", 1, 32)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(200, 30, 30));
        jLabel4.setText("Pemagangan LPK");
        jLabel4.setPreferredSize(new java.awt.Dimension(400, 50));
        pnlLeft.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(200, 30, 30));
        jSeparator1.setPreferredSize(new java.awt.Dimension(80, 4));
        pnlLeft.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(100, 100, 100));
        jLabel5.setText("dan laporan magang secara terintegrasi dan efisien");
        jLabel5.setPreferredSize(new java.awt.Dimension(450, 50));
        pnlLeft.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 30));

        pnlIkon1.setBackground(new java.awt.Color(255, 235, 235));
        pnlIkon1.setPreferredSize(new java.awt.Dimension(44, 44));
        pnlIkon1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/group (1).png")); // NOI18N
        jLabel6.setText("i");
        jLabel6.setPreferredSize(new java.awt.Dimension(24, 24));
        pnlIkon1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pnlLeft.add(pnlIkon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jLabel7.setText("Manajemen Peserta");
        jLabel7.setPreferredSize(new java.awt.Dimension(260, 20));
        pnlLeft.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 210, 210));
        jLabel8.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        jLabel8.setText("Kelola data peserta magang dengan mudah");
        pnlLeft.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 362, -1, -1));

        pnlIkon2.setBackground(new java.awt.Color(255, 235, 235));
        pnlIkon2.setPreferredSize(new java.awt.Dimension(44, 44));
        pnlIkon2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/city.png")); // NOI18N
        pnlIkon2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pnlLeft.add(pnlIkon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jLabel10.setText("Penempatan Magang");
        pnlLeft.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 210, 210));
        jLabel11.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        jLabel11.setText("Kelola penempatan ke perusahaan/instansi");
        pnlLeft.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        pnlIkon3.setBackground(new java.awt.Color(255, 235, 235));
        pnlIkon3.setPreferredSize(new java.awt.Dimension(44, 44));
        pnlIkon3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/clipboard.png")); // NOI18N
        pnlIkon3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pnlLeft.add(pnlIkon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        jLabel13.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jLabel13.setText("Monitoring & Penilaian");
        pnlLeft.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 210, 210));
        jLabel14.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(30, 30, 30));
        jLabel14.setText("Pantau aktivitas & kinerja peserta");
        pnlLeft.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 482, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 235, 235));
        jPanel1.setPreferredSize(new java.awt.Dimension(44, 44));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/pie-chart.png")); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pnlLeft.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jLabel16.setText("Laporan & Analitik");
        pnlLeft.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, -1, -1));

        jLabel17.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(30, 30, 30));
        jLabel17.setText("Laporan lengkap & analitik ");
        pnlLeft.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 542, -1, -1));

        pnlRight.setBackground(new java.awt.Color(255, 255, 255));
        pnlRight.setPreferredSize(new java.awt.Dimension(480, 680));
        pnlRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 235, 235));
        jPanel2.setPreferredSize(new java.awt.Dimension(70, 70));

        jLabel25.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/enter (1).png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(18, 18, 18))
        );

        pnlRight.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel18.setFont(new java.awt.Font("Inter", 1, 22)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Selamat Datang");
        pnlRight.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel19.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(30, 30, 30));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Silahkan masuk Untuk Melanjutkan");
        pnlRight.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jLabel22.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(50, 50, 50));
        jLabel22.setText("Username");
        pnlRight.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        txtUsername.setBackground(new java.awt.Color(250, 250, 250));
        pnlRight.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 400, 50));

        jLabel23.setText("Password");
        pnlRight.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        txtPassword.setBackground(new java.awt.Color(250, 250, 250));
        pnlRight.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 400, 50));

        jButton1.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jButton1.setText("Lupa password?");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(100, 20));
        pnlRight.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 120, -1));

        btnLogin.setBackground(new java.awt.Color(122, 0, 0));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Masuk");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlRight.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 400, 60));

        pnlLeft.add(pnlRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, 570));

        jLabel20.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel20.setText("LEMBAGA");
        jLabel20.setPreferredSize(new java.awt.Dimension(200, 20));
        pnlLeft.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 60, -1));

        jLabel21.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel21.setText("PELATIHAN");
        jLabel21.setPreferredSize(new java.awt.Dimension(200, 20));
        pnlLeft.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 60, -1));

        jLabel24.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(100, 100, 100));
        jLabel24.setText("Kelola data peserta, penempatan, aktivitas, penilaian, laporan");
        jLabel24.setPreferredSize(new java.awt.Dimension(450, 50));
        pnlLeft.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        bgImg.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/bg (1).png")); // NOI18N
        bgImg.setPreferredSize(new java.awt.Dimension(1100, 686));
        pnlLeft.add(bgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(pnlLeft, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String inputUsername = txtUsername.getText().trim();
        String inputPassword = new String(txtPassword.getPassword()); 

        if (inputUsername.isEmpty() || inputPassword.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Username dan Password tidak boleh kosong!", 
                "Peringatan", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        boolean loginSukses = false;

        for (Model.Pengguna user : DataStore.DataStore.daftarPengguna) {
            if (user.validasiLogin(inputUsername, inputPassword)) {
                loginSukses = true;
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Selamat Datang, " + user.getNamaLengkap() + "!\n" + user.getMenuOtoritas(), 
                    "Login Berhasil", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

                if (user.getRole().equals("ADMIN")) {
                    Views.AdminFrame adminDashboard = new Views.AdminFrame(); 
                    adminDashboard.setVisible(true);
                } else if (user.getRole().equals("INSTRUKTUR")) {
                    Model.Instruktur ins = (Model.Instruktur) user;
                    String idYangLogin = ins.getIdInstruktur(); 
                    
                    Views.instruktur.InstrukturFrame instrukturDashboard = new Views.instruktur.InstrukturFrame(idYangLogin);
                    instrukturDashboard.setVisible(true);
                    
                }
                this.dispose();
                break;
            }
        }

        if (!loginSukses) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Username atau Password salah! Silakan coba lagi.", 
                "Login Gagal", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImg;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlIkon1;
    private javax.swing.JPanel pnlIkon2;
    private javax.swing.JPanel pnlIkon3;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
