/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views;

import DataStore.DataStore;
import Model.Peserta;
import Model.Seleksi;
import javax.swing.JOptionPane;

/**
 *
 * @author arelssi
 */
public class FormInputSeleksi extends javax.swing.JDialog {

    /**
     * Creates new form FormInputSeleksi
     */
    private Peserta pesertaAktif;
    
    public FormInputSeleksi(java.awt.Frame parent, boolean modal, String idPeserta) {
        super(parent, modal);
        initComponents();
        txtIdSeleksi.setEditable(false);
        
        setupComboBox();
        loadDataPeserta(idPeserta);
    }
    
    private void setupComboBox() {
        // Asumsi nama ComboBox: cbSpesialisasi dan cbStatusKelulusan
        cbSpesialisasi.removeAllItems();
        cbSpesialisasi.addItem("Seleksi Bahasa Jepang");
        cbSpesialisasi.addItem("Seleksi Wawancara");
        cbSpesialisasi.addItem("Tes Fisik & Kesamaptaan");
        cbSpesialisasi.addItem("Wawancara User (Manufaktur)");
        cbSpesialisasi.addItem("Wawancara User (Kaigo)");

        cbStatusKelulusan.removeAllItems();
        cbStatusKelulusan.addItem("Lulus");
        cbStatusKelulusan.addItem("Mengulang");
        cbStatusKelulusan.addItem("Gugur Permanen");
    }
    
    private void loadDataPeserta(String idPeserta) {
        // 1. Cari objek Peserta
        for (Peserta p : DataStore.daftarPeserta) {
            if (p.getIdPeserta().equals(idPeserta)) {
                pesertaAktif = p;
                break;
            }
        }

        if (pesertaAktif != null) {
            // Set Header Info
            lblNamaPeserta.setText(pesertaAktif.getNamaLengkap());
            // Gabungkan ID dan Level Bahasa (mengakali desain "Level N3 Level N3")
            lblInfoPeserta.setText(pesertaAktif.getIdPeserta() + "   Level " + pesertaAktif.getLevelBahasa());

            // 2. Hitung jumlah riwayat seleksi sebelumnya
            int riwayatSebelumnya = 0;
            for (Seleksi s : DataStore.daftarSeleksi) {
                if (s.getPeserta().getIdPeserta().equals(idPeserta)) {
                    riwayatSebelumnya++;
                }
            }

            // 3. Logika Percobaan (Maksimal 3x)
            int maksimalPercobaan = 3;
            int percobaanSekarang = riwayatSebelumnya + 1;
            int sisaPercobaan = maksimalPercobaan - percobaanSekarang;

            if (percobaanSekarang > maksimalPercobaan) {
                lblPercobaan.setText("Kesempatan Habis!");
                lblPercobaan.setForeground(java.awt.Color.RED);
                btnSimpan.setEnabled(false); // Kunci tombol simpan jika jatah habis
            } else {
                lblPercobaan.setText(percobaanSekarang + " dari " + maksimalPercobaan + " - sisa " + sisaPercobaan);
            }

            int nextId = DataStore.daftarSeleksi.size() + 1;
            txtIdSeleksi.setText(String.format("SEL%03d", nextId));
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        panelBody = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdSeleksi = new javax.swing.JTextField();
        txtNilaiSeleksi = new javax.swing.JTextField();
        txtTanggalSeleksi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbSpesialisasi = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblNamaPeserta = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblInfoPeserta = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblPercobaan = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        cbStatusKelulusan = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        panelFooter = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(122, 0, 0));
        panelHeader.setPreferredSize(new java.awt.Dimension(520, 68));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Input Hasil Seleksi");
        jLabel1.setPreferredSize(new java.awt.Dimension(280, 22));
        panelHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 14, -1, -1));

        jLabel2.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Masukkan nilai dan hasil seleksi peserta");
        jLabel2.setPreferredSize(new java.awt.Dimension(300, 16));
        panelHeader.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 38, -1, -1));

        jButton1.setBackground(new java.awt.Color(160, 20, 20));
        jButton1.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(30, 30));
        panelHeader.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 18, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/videocall (1).png")); // NOI18N
        jLabel11.setText("Icon");
        jLabel11.setPreferredSize(new java.awt.Dimension(36, 36));
        panelHeader.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 18, -1, -1));

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelBody.setBackground(new java.awt.Color(248, 248, 248));
        panelBody.setPreferredSize(new java.awt.Dimension(520, 364));
        panelBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setPreferredSize(new java.awt.Dimension(480, 8));
        panelBody.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(60, 60, 60));
        jLabel4.setText("ID Seleksi");
        jLabel4.setPreferredSize(new java.awt.Dimension(140, 14));
        panelBody.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(60, 60, 60));
        jLabel5.setText("Tanggal Seleksi");
        jLabel5.setPreferredSize(new java.awt.Dimension(140, 14));
        panelBody.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        txtIdSeleksi.setEditable(false);
        txtIdSeleksi.setBackground(new java.awt.Color(245, 245, 245));
        txtIdSeleksi.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        txtIdSeleksi.setForeground(new java.awt.Color(160, 160, 160));
        txtIdSeleksi.setPreferredSize(new java.awt.Dimension(220, 34));
        panelBody.add(txtIdSeleksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 127, -1, -1));

        txtNilaiSeleksi.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        txtNilaiSeleksi.setForeground(new java.awt.Color(30, 30, 30));
        txtNilaiSeleksi.setPreferredSize(new java.awt.Dimension(480, 34));
        txtNilaiSeleksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNilaiSeleksiKeyReleased(evt);
            }
        });
        panelBody.add(txtNilaiSeleksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 220, -1));

        txtTanggalSeleksi.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        txtTanggalSeleksi.setForeground(new java.awt.Color(30, 30, 30));
        txtTanggalSeleksi.setPreferredSize(new java.awt.Dimension(230, 34));
        panelBody.add(txtTanggalSeleksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 127, -1, -1));

        jLabel8.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(30, 30, 30));
        jLabel8.setText("Spesialisasi");
        jLabel8.setPreferredSize(new java.awt.Dimension(160, 14));
        panelBody.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Inter", 0, 8)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(70, 70, 70));
        jLabel9.setText("nilai lebih dari atau sama dengan 70.");
        jLabel9.setPreferredSize(new java.awt.Dimension(160, 14));
        panelBody.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 343, 420, -1));

        cbSpesialisasi.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        cbSpesialisasi.setForeground(new java.awt.Color(30, 30, 30));
        cbSpesialisasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbSpesialisasi.setPreferredSize(new java.awt.Dimension(480, 34));
        panelBody.add(cbSpesialisasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        lblNamaPeserta.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        lblNamaPeserta.setText("Muhamad Farel Fauzan");
        jPanel1.add(lblNamaPeserta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel10.setText("Level N3");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 35, -1, -1));

        lblInfoPeserta.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        lblInfoPeserta.setText("PST-001");
        jPanel1.add(lblInfoPeserta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 35, -1, -1));

        jLabel13.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel13.setText("Level N3");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 35, -1, -1));

        lblPercobaan.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblPercobaan.setForeground(new java.awt.Color(122, 0, 0));
        lblPercobaan.setText("2 dari 3 - sisa 1");
        jPanel1.add(lblPercobaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jLabel15.setFont(new java.awt.Font("Inter", 0, 8)); // NOI18N
        jLabel15.setText("Percobaan Seleksi");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, 20));

        panelBody.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 70));

        jLabel16.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(122, 0, 0));
        jLabel16.setText("DATA SELEKSI");
        jLabel16.setPreferredSize(new java.awt.Dimension(200, 14));
        panelBody.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel17.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(122, 0, 0));
        jLabel17.setText("HASIL SELEKSI");
        jLabel17.setPreferredSize(new java.awt.Dimension(200, 14));
        panelBody.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jSeparator4.setPreferredSize(new java.awt.Dimension(480, 8));
        panelBody.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel18.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(30, 30, 30));
        jLabel18.setText("Status Kelulusan");
        jLabel18.setPreferredSize(new java.awt.Dimension(160, 14));
        panelBody.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        cbStatusKelulusan.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        cbStatusKelulusan.setForeground(new java.awt.Color(30, 30, 30));
        cbStatusKelulusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbStatusKelulusan.setPreferredSize(new java.awt.Dimension(480, 34));
        panelBody.add(cbStatusKelulusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 230, -1));

        jLabel19.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(30, 30, 30));
        jLabel19.setText("Nilai Seleksi");
        jLabel19.setPreferredSize(new java.awt.Dimension(160, 14));
        panelBody.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel20.setFont(new java.awt.Font("Inter", 0, 8)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(70, 70, 70));
        jLabel20.setText("Skala 0 sampai 100. Peserta dinyatakan lulus jika ");
        jLabel20.setPreferredSize(new java.awt.Dimension(160, 14));
        panelBody.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 420, -1));

        getContentPane().add(panelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, -1, -1));

        panelFooter.setBackground(new java.awt.Color(248, 248, 248));
        panelFooter.setPreferredSize(new java.awt.Dimension(520, 58));
        panelFooter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setPreferredSize(new java.awt.Dimension(520, 2));
        panelFooter.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnBatal.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(80, 80, 80));
        btnBatal.setText("Batal");
        btnBatal.setToolTipText("Batal");
        btnBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBatal.setFocusPainted(false);
        btnBatal.setPreferredSize(new java.awt.Dimension(100, 34));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        panelFooter.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 12, -1, -1));

        btnSimpan.setBackground(new java.awt.Color(122, 0, 0));
        btnSimpan.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorderPainted(false);
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.setFocusPainted(false);
        btnSimpan.setPreferredSize(new java.awt.Dimension(116, 34));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        panelFooter.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 12, -1, -1));

        getContentPane().add(panelFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 432, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNilaiSeleksiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNilaiSeleksiKeyReleased
        try {
            int nilai = Integer.parseInt(txtNilaiSeleksi.getText());
            if (nilai >= 70) {
                cbStatusKelulusan.setSelectedItem("Lulus");
            } else {
                cbStatusKelulusan.setSelectedItem("Mengulang");
            }
        } catch (NumberFormatException e) {
            // Biarkan saja jika yang diketik bukan angka/masih kosong
        }
    }//GEN-LAST:event_txtNilaiSeleksiKeyReleased

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (txtTanggalSeleksi.getText().trim().isEmpty() || txtNilaiSeleksi.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tanggal dan Nilai tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Validasi Nilai harus berupa angka 0-100
            int nilai = Integer.parseInt(txtNilaiSeleksi.getText());
            if (nilai < 0 || nilai > 100) {
                JOptionPane.showMessageDialog(this, "Nilai seleksi harus berada di antara 0 sampai 100!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Ambil data dari form
            String idSel = txtIdSeleksi.getText();
            String tanggal = txtTanggalSeleksi.getText();
            String jenis = cbSpesialisasi.getSelectedItem().toString();
            String statusHasil = cbStatusKelulusan.getSelectedItem().toString();

            // BUNGKUS JADI OBJEK BARU & SIMPAN KE DATASTORE
            Seleksi seleksiBaru = new Seleksi(idSel, pesertaAktif, jenis, tanggal, nilai, statusHasil);
            DataStore.daftarSeleksi.add(seleksiBaru);

            // LOGIKA BISNIS: Update status peserta jika Lulus / Gugur Permanen
            if (statusHasil.equals("Lulus")) {
                pesertaAktif.setStatusSeleksi("Lulus");
                // Jika ingin langsung mengaitkan ke halaman dokumen:
                pesertaAktif.setStatusKeberangkatan("Menunggu Dokumen"); 
            } else if (statusHasil.equals("Gugur Permanen")) {
                pesertaAktif.setStatusSeleksi("Gugur");
                pesertaAktif.setStatusKeberangkatan("Dibatalkan");
            }

            JOptionPane.showMessageDialog(this, "Hasil seleksi berhasil disimpan!");
            this.dispose(); // Tutup form

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input Nilai harus berupa angka (bilangan bulat)!", "Error Input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbSpesialisasi;
    private javax.swing.JComboBox<String> cbStatusKelulusan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblInfoPeserta;
    private javax.swing.JLabel lblNamaPeserta;
    private javax.swing.JLabel lblPercobaan;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTextField txtIdSeleksi;
    private javax.swing.JTextField txtNilaiSeleksi;
    private javax.swing.JTextField txtTanggalSeleksi;
    // End of variables declaration//GEN-END:variables
}
