/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views;

/**
 *
 * @author arelssi
 */
public class FormTambahInstruktur extends javax.swing.JDialog {

    /**
     * Creates new form FormTambahInstruktur
     */
    public FormTambahInstruktur(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(520, 490);
        pack();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Tambah Instruktur Baru");
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelBody = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdInstruktur = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbSpesialisasi = new javax.swing.JComboBox<>();
        cmbLevelJLPT = new javax.swing.JComboBox<>();
        cmbKelas = new javax.swing.JComboBox<>();
        panelFooter = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(122, 0, 0));
        panelHeader.setPreferredSize(new java.awt.Dimension(520, 68));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tambah Instruktur Baru");
        jLabel1.setPreferredSize(new java.awt.Dimension(280, 22));
        panelHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 14, -1, -1));

        jLabel2.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Isi data instruktur dengan benar");
        jLabel2.setPreferredSize(new java.awt.Dimension(300, 16));
        panelHeader.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 38, -1, -1));

        jButton1.setBackground(new java.awt.Color(160, 20, 20));
        jButton1.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(30, 30));
        panelHeader.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 18, -1, -1));

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelBody.setBackground(new java.awt.Color(248, 248, 248));
        panelBody.setPreferredSize(new java.awt.Dimension(520, 364));
        panelBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(122, 0, 0));
        jLabel3.setText("DATA IDENTITAS");
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 14));
        panelBody.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, -1, -1));

        jSeparator1.setPreferredSize(new java.awt.Dimension(480, 8));
        panelBody.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 32, -1, -1));

        jLabel4.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(60, 60, 60));
        jLabel4.setText("ID Instruktur");
        jLabel4.setPreferredSize(new java.awt.Dimension(140, 14));
        panelBody.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 44, -1, -1));

        jLabel5.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(60, 60, 60));
        jLabel5.setText("No. Telp");
        jLabel5.setPreferredSize(new java.awt.Dimension(140, 14));
        panelBody.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 44, -1, -1));

        jLabel6.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(60, 60, 60));
        jLabel6.setText("Nama Instruktur");
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 14));
        panelBody.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 102, -1, -1));

        txtIdInstruktur.setEditable(false);
        txtIdInstruktur.setBackground(new java.awt.Color(245, 245, 245));
        txtIdInstruktur.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        txtIdInstruktur.setForeground(new java.awt.Color(160, 160, 160));
        txtIdInstruktur.setText("jTextField1");
        txtIdInstruktur.setPreferredSize(new java.awt.Dimension(220, 34));
        panelBody.add(txtIdInstruktur, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jTextField2.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(30, 30, 30));
        jTextField2.setPreferredSize(new java.awt.Dimension(480, 34));
        panelBody.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 118, -1, -1));

        jTextField3.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(30, 30, 30));
        jTextField3.setPreferredSize(new java.awt.Dimension(230, 34));
        panelBody.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(122, 0, 0));
        jLabel7.setText("DATA KEAHLIAN");
        jLabel7.setPreferredSize(new java.awt.Dimension(200, 14));
        panelBody.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 168, -1, -1));

        jSeparator2.setPreferredSize(new java.awt.Dimension(480, 8));
        panelBody.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 184, -1, -1));

        jLabel8.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(30, 30, 30));
        jLabel8.setText("Spesialisasi");
        jLabel8.setPreferredSize(new java.awt.Dimension(160, 14));
        panelBody.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 196, -1, -1));

        jLabel9.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 30, 30));
        jLabel9.setText("Level JLPT");
        jLabel9.setPreferredSize(new java.awt.Dimension(160, 14));
        panelBody.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 254, -1, -1));

        jLabel10.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(30, 30, 30));
        jLabel10.setText("Kelas Diampu");
        jLabel10.setPreferredSize(new java.awt.Dimension(160, 14));
        panelBody.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 254, -1, -1));

        cmbSpesialisasi.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        cmbSpesialisasi.setForeground(new java.awt.Color(30, 30, 30));
        cmbSpesialisasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSpesialisasi.setPreferredSize(new java.awt.Dimension(480, 34));
        panelBody.add(cmbSpesialisasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 212, -1, -1));

        cmbLevelJLPT.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        cmbLevelJLPT.setForeground(new java.awt.Color(30, 30, 30));
        cmbLevelJLPT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbLevelJLPT.setPreferredSize(new java.awt.Dimension(220, 34));
        panelBody.add(cmbLevelJLPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        cmbKelas.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        cmbKelas.setForeground(new java.awt.Color(30, 30, 30));
        cmbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbKelas.setPreferredSize(new java.awt.Dimension(230, 34));
        panelBody.add(cmbKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        getContentPane().add(panelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, -1, -1));

        panelFooter.setBackground(new java.awt.Color(248, 248, 248));
        panelFooter.setPreferredSize(new java.awt.Dimension(520, 58));
        panelFooter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setPreferredSize(new java.awt.Dimension(520, 2));
        panelFooter.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnBatal.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(80, 80, 80));
        btnBatal.setText("Batal");
        btnBatal.setToolTipText("Batal");
        btnBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBatal.setFocusPainted(false);
        btnBatal.setPreferredSize(new java.awt.Dimension(100, 34));
        panelFooter.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 12, -1, -1));

        btnSimpan.setBackground(new java.awt.Color(122, 0, 0));
        btnSimpan.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorderPainted(false);
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.setFocusPainted(false);
        btnSimpan.setPreferredSize(new java.awt.Dimension(116, 34));
        panelFooter.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 12, -1, -1));

        getContentPane().add(panelFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 432, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTambahInstruktur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTambahInstruktur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTambahInstruktur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTambahInstruktur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormTambahInstruktur dialog = new FormTambahInstruktur(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbKelas;
    private javax.swing.JComboBox<String> cmbLevelJLPT;
    private javax.swing.JComboBox<String> cmbSpesialisasi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTextField txtIdInstruktur;
    // End of variables declaration//GEN-END:variables
}
