/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DataStore.DataStore;
import Model.Instruktur;
import Model.Peserta;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author arelssi
 */
    public class FormTambahPeserta extends javax.swing.JFrame {

        // Method untuk membuat ID Otomatis
    private String generateIdPeserta() {
        // Mengambil jumlah data yang ada di ArrayList
        int ukuranData = DataStore.daftarPeserta.size();
        
        // Format ID: PST + 3 digit angka (PST001, PST002, dst)
        return String.format("PST%03d", ukuranData + 1);
    }

    // Method untuk mengisi ComboBox dengan Objek Instruktur
    private void loadComboBoxInstruktur() {
        cmbInstruktur.removeAllItems();
        
        // Ambil khusus data instruktur dari DataStore
        for (Instruktur ins : DataStore.getHanyaInstruktur()) {
            cmbInstruktur.addItem(ins); // Menambahkan objek utuh, bukan cuma teks
        }
    }
    
    

    public FormTambahPeserta(java.awt.Frame parent, boolean modal) {
        initComponents();
        setSize(560, 620);
        pack();
        setLocationRelativeTo(parent);
        setResizable(false);
        setTitle("Tambah Peserta Baru");
        
        // Atur ID Peserta agar otomatis terisi dan tidak bisa diedit manual
        txtIdPeserta.setText(generateIdPeserta());
        txtIdPeserta.setEditable(false);
        
        // Panggil method untuk mengisi ComboBox
        loadComboBoxInstruktur();
        // Contoh isi manual untuk Level Bahasa
        cmbLevelBahasa.setModel(new DefaultComboBoxModel<>(new String[]{"N5", "N4", "N3"}));
        // Status Pembayaran
        cmbStatusBayar.setModel(new DefaultComboBoxModel<>(new String[]{"Belum Lunas", "Lunas"}));
        cmbAgama.setModel(new DefaultComboBoxModel<>(new String[]{"Islam", "Kristen", "Hindu", "Katholik", "Budha"}));
        cmbJenisKelamin.setModel(new DefaultComboBoxModel<>(new String[]{"Laki-laki", "Perempuan"}));
        cmbProgram.setModel(new DefaultComboBoxModel<>(new String[]{"Manufaktur", "Caregiver", "Pertanian"}));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelBody = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtIdPeserta = new javax.swing.JTextField();
        txtNik = new javax.swing.JTextField();
        txtNamaLengkap = new javax.swing.JTextField();
        txtTanggalLahir = new javax.swing.JTextField();
        txtNoHp = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        cmbJenisKelamin = new javax.swing.JComboBox<>();
        cmbAgama = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmbProgram = new javax.swing.JComboBox<>();
        cmbInstruktur = new javax.swing.JComboBox();
        cmbLevelBahasa = new javax.swing.JComboBox<>();
        cmbStatusBayar = new javax.swing.JComboBox<>();
        footer = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(122, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(560, 68));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/videocall (1).png")); // NOI18N
        jLabel1.setText("Icon");
        jLabel1.setPreferredSize(new java.awt.Dimension(36, 36));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 18, -1, -1));

        jLabel2.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tambah Peserta Baru");
        jLabel2.setPreferredSize(new java.awt.Dimension(280, 22));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 14, -1, -1));

        jLabel3.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 200, 200));
        jLabel3.setText("Isi seluruh data peserta dengan benar");
        jLabel3.setPreferredSize(new java.awt.Dimension(300, 16));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 38, -1, -1));

        jButton1.setBackground(new java.awt.Color(160, 20, 20));
        jButton1.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 18, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelBody.setBackground(new java.awt.Color(255, 255, 255));
        panelBody.setPreferredSize(new java.awt.Dimension(560, 470));
        panelBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(122, 0, 0));
        jLabel4.setText("DATA PRIBADI");
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 14));
        panelBody.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, -1, -1));

        jSeparator1.setPreferredSize(new java.awt.Dimension(520, 8));
        panelBody.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 32, -1, -1));

        jLabel5.setText("ID Peserta");
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 14));
        panelBody.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 44, -1, -1));

        jLabel6.setText("NIK *");
        jLabel6.setPreferredSize(new java.awt.Dimension(120, 14));
        panelBody.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 44, -1, -1));

        jLabel7.setText("Nama Lengkap");
        jLabel7.setPreferredSize(new java.awt.Dimension(200, 14));
        panelBody.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 102, -1, -1));

        jLabel8.setText("Tanggal Lahir");
        jLabel8.setPreferredSize(new java.awt.Dimension(160, 14));
        panelBody.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel9.setText("Jenis Kelamin");
        jLabel9.setPreferredSize(new java.awt.Dimension(160, 14));
        panelBody.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jLabel10.setText("No. HP");
        panelBody.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 218, -1, -1));

        jLabel11.setText("Agama");
        panelBody.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 218, -1, -1));

        jLabel12.setText("Alamat");
        jLabel12.setPreferredSize(new java.awt.Dimension(120, 14));
        panelBody.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 276, -1, -1));

        txtIdPeserta.setEditable(false);
        txtIdPeserta.setBackground(new java.awt.Color(245, 245, 245));
        txtIdPeserta.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        txtIdPeserta.setForeground(new java.awt.Color(160, 160, 160));
        txtIdPeserta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 210, 210)));
        txtIdPeserta.setPreferredSize(new java.awt.Dimension(240, 34));
        panelBody.add(txtIdPeserta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtNik.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        txtNik.setForeground(new java.awt.Color(60, 60, 60));
        txtNik.setPreferredSize(new java.awt.Dimension(250, 34));
        panelBody.add(txtNik, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        txtNamaLengkap.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        txtNamaLengkap.setForeground(new java.awt.Color(60, 60, 60));
        txtNamaLengkap.setPreferredSize(new java.awt.Dimension(520, 34));
        panelBody.add(txtNamaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 118, -1, -1));

        txtTanggalLahir.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        txtTanggalLahir.setForeground(new java.awt.Color(60, 60, 60));
        txtTanggalLahir.setText("YYYY-MM-DD");
        txtTanggalLahir.setPreferredSize(new java.awt.Dimension(240, 34));
        panelBody.add(txtTanggalLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 176, -1, -1));

        txtNoHp.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        txtNoHp.setForeground(new java.awt.Color(60, 60, 60));
        txtNoHp.setPreferredSize(new java.awt.Dimension(240, 34));
        panelBody.add(txtNoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 234, -1, -1));

        txtAlamat.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        txtAlamat.setForeground(new java.awt.Color(60, 60, 60));
        txtAlamat.setPreferredSize(new java.awt.Dimension(520, 34));
        panelBody.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 292, -1, -1));

        cmbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbJenisKelamin.setPreferredSize(new java.awt.Dimension(250, 34));
        panelBody.add(cmbJenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 176, -1, -1));

        cmbAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAgama.setPreferredSize(new java.awt.Dimension(250, 34));
        panelBody.add(cmbAgama, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 234, -1, -1));

        jLabel13.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(122, 0, 0));
        jLabel13.setText("DATA PROGRAM & AKADEMIK");
        jLabel13.setPreferredSize(new java.awt.Dimension(280, 14));
        panelBody.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 342, -1, -1));

        jSeparator2.setPreferredSize(new java.awt.Dimension(520, 8));
        panelBody.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 358, -1, -1));

        jLabel14.setText("Program");
        panelBody.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel15.setText("Instruktur");
        panelBody.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 368, -1, -1));

        jLabel16.setText("Level bahasa");
        jLabel16.setPreferredSize(new java.awt.Dimension(120, 14));
        panelBody.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 426, 100, -1));

        jLabel17.setText("Status Pembayaran");
        panelBody.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 426, -1, -1));

        cmbProgram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProgram.setPreferredSize(new java.awt.Dimension(240, 34));
        panelBody.add(cmbProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 384, -1, -1));

        cmbInstruktur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbInstruktur.setPreferredSize(new java.awt.Dimension(250, 34));
        panelBody.add(cmbInstruktur, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 384, -1, -1));

        cmbLevelBahasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbLevelBahasa.setPreferredSize(new java.awt.Dimension(240, 34));
        panelBody.add(cmbLevelBahasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 442, -1, -1));

        cmbStatusBayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStatusBayar.setPreferredSize(new java.awt.Dimension(250, 34));
        panelBody.add(cmbStatusBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 442, -1, -1));

        getContentPane().add(panelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, -1, 490));

        footer.setBackground(new java.awt.Color(248, 248, 248));
        footer.setPreferredSize(new java.awt.Dimension(560, 58));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setForeground(new java.awt.Color(220, 220, 220));
        jSeparator3.setPreferredSize(new java.awt.Dimension(560, 2));
        footer.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton2.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(80, 80, 80));
        jButton2.setText("Batal");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 210, 210)));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 34));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        footer.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 12, -1, -1));

        btnSimpan.setBackground(new java.awt.Color(122, 0, 0));
        btnSimpan.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorderPainted(false);
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.setFocusPainted(false);
        btnSimpan.setPreferredSize(new java.awt.Dimension(118, 34));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        footer.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 12, -1, -1));

        getContentPane().add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int konfirm = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Data yang diisi akan hilang. Yakin ingin membatalkan?",
        "Konfirmasi Batal",
        javax.swing.JOptionPane.YES_NO_OPTION,
        javax.swing.JOptionPane.WARNING_MESSAGE
    );
    if (konfirm == javax.swing.JOptionPane.YES_OPTION) {
        this.dispose();
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    // 1. Validasi Input Dasar (Contoh NIK dan Nama harus diisi)
        if (txtNik.getText().trim().isEmpty() || txtNamaLengkap.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Harap isi NIK dan Nama Lengkap dengan benar!", 
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return; // Hentikan proses simpan
        }

        try {
            // 2. Ambil semua data dari komponen GUI
            String id = txtIdPeserta.getText();
            String nik = txtNik.getText();
            String nama = txtNamaLengkap.getText();
            String tglLahir = txtTanggalLahir.getText();
            String jk = cmbJenisKelamin.getSelectedItem().toString();
            String noHp = txtNoHp.getText();
            String agama = cmbAgama.getSelectedItem().toString();
            String alamat = txtAlamat.getText();
            String program = cmbProgram.getSelectedItem().toString();
            String level = cmbLevelBahasa.getSelectedItem().toString();
            String bayar = cmbStatusBayar.getSelectedItem().toString();

            // 3. Ambil Objek Instruktur terpilih dari ComboBox (Casting Object)
            Instruktur instrukturPilihan = (Instruktur) cmbInstruktur.getSelectedItem();

            // 4. Buat instance Objek Peserta Baru
            Peserta pesertaBaru = new Peserta(
                id, nik, nama, tglLahir, jk, noHp, agama, alamat, 
                program, instrukturPilihan, level, bayar
            );

            // 5. Simpan ke dalam In-Memory DataStore
            DataStore.daftarPeserta.add(pesertaBaru);

            // 6. Tampilkan pesan sukses dan tutup jendela Form
            JOptionPane.showMessageDialog(this, "Data Peserta Baru Berhasil Disimpan!");
            this.dispose(); 
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Terjadi kesalahan saat menyimpan data: " + e.getMessage(), 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTambahPeserta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTambahPeserta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTambahPeserta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTambahPeserta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTambahPeserta(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbAgama;
    private javax.swing.JComboBox cmbInstruktur;
    private javax.swing.JComboBox<String> cmbJenisKelamin;
    private javax.swing.JComboBox<String> cmbLevelBahasa;
    private javax.swing.JComboBox<String> cmbProgram;
    private javax.swing.JComboBox<String> cmbStatusBayar;
    private javax.swing.JPanel footer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel panelBody;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtIdPeserta;
    private javax.swing.JTextField txtNamaLengkap;
    private javax.swing.JTextField txtNik;
    private javax.swing.JTextField txtNoHp;
    private javax.swing.JTextField txtTanggalLahir;
    // End of variables declaration//GEN-END:variables
}
