/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import DataStore.DataStore;
import Model.Peserta;
import java.awt.Color;
import java.awt.Font;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arelssi
 */
public class PanelAdmin extends javax.swing.JPanel {
    // --- 1. UPDATE: Metode loadStatistics Tanpa Database ---
    private void loadStatistics() {
        int totalPeserta = DataStore.daftarPeserta.size();
        int lulus = 0;
        int gugur = 0;

        // Iterasi (Looping) data dari ArrayList
        for (Peserta p : DataStore.daftarPeserta) {
            if (p.getStatusSeleksi().equalsIgnoreCase("Lulus")) {
                lulus++;
            } else if (p.getStatusSeleksi().equalsIgnoreCase("Gugur Permanen") || 
                       p.getStatusSeleksi().equalsIgnoreCase("Gugur")) {
                gugur++;
            }
        }

        // Memanggil method khusus instruktur yang sudah kita buat sebelumnya
        int totalInstruktur = DataStore.getHanyaInstruktur().size();

        // Tampilkan ke JLabel
        lblTotalPeserta.setText(String.valueOf(totalPeserta));
        lblPesertaLulus.setText(String.valueOf(lulus));
        lblPesertaGugur.setText(String.valueOf(gugur));
        lblTotalInstruktur.setText(String.valueOf(totalInstruktur));
    }

    // --- 2. UPDATE: Metode loadTableData Tanpa Database ---
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) tabelPeserta.getModel();
        model.setRowCount(0); // Kosongkan tabel sebelum diisi ulang
        
        // Panggil utilitas resize kolom Anda jika ada
        try {
            Util.TabelUtil.autoResizeKolom(tabelPeserta);
        } catch (Exception e) {
            System.out.println("TabelUtil belum tersedia: " + e.getMessage());
        }

        int no = 1;
        // Mengisi tabel dengan data dari Objek di dalam ArrayList
        for (Peserta p : DataStore.daftarPeserta) {
            model.addRow(new Object[]{
                no++,
                p.getIdPeserta(),
                p.getNamaLengkap(),
                p.getLevelBahasa(),
                p.getProgram(),
                p.getStatusSeleksi(),
                p.getStatusPembayaran(),
                p.getStatusKeberangkatan()
            });
        }
    }
    public PanelAdmin() {
        initComponents();
        tabelPeserta.getTableHeader().setFont(new Font("Inter", Font.BOLD, 12));
        tabelPeserta.getTableHeader().setOpaque(false);
        tabelPeserta.getTableHeader().setBackground(new Color(122, 0, 0));
        tabelPeserta.getTableHeader().setForeground(new Color(255, 255, 255));
        
        loadStatistics();
        loadTableData();
        
        setPreferredSize(new java.awt.Dimension(980, 616));
        setBackground(new java.awt.Color(245, 245, 245));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContent = new javax.swing.JPanel();
        panelKartu1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblTotalPeserta = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelKartu2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblPesertaLulus = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        panelKartu3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        lblPesertaGugur = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        panelkartu4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblTotalInstruktur = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPeserta = new javax.swing.JTable();
        btnTambahPeserta = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainContent.setBackground(new java.awt.Color(245, 245, 245));
        mainContent.setName("mainContent"); // NOI18N
        mainContent.setPreferredSize(new java.awt.Dimension(980, 616));
        mainContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelKartu1.setBackground(new java.awt.Color(255, 255, 255));
        panelKartu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        panelKartu1.setPreferredSize(new java.awt.Dimension(210, 100));
        panelKartu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Inter", 0, 22)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/user-solid (1) (1).png")); // NOI18N
        jLabel13.setText("s");
        jLabel13.setPreferredSize(new java.awt.Dimension(36, 36));
        panelKartu1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 60, 60));

        jLabel14.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(130, 130, 130));
        jLabel14.setText("Total Peserta");
        jLabel14.setPreferredSize(new java.awt.Dimension(140, 16));
        panelKartu1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 14, -1, -1));

        lblTotalPeserta.setFont(new java.awt.Font("Inter", 1, 28)); // NOI18N
        lblTotalPeserta.setForeground(new java.awt.Color(122, 0, 0));
        lblTotalPeserta.setText("10");
        lblTotalPeserta.setPreferredSize(new java.awt.Dimension(100, 36));
        panelKartu1.add(lblTotalPeserta, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 34, -1, -1));

        jLabel16.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(170, 170, 170));
        jLabel16.setText("Peserta Terdaftar");
        jLabel16.setPreferredSize(new java.awt.Dimension(140, 16));
        panelKartu1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 72, -1, -1));

        mainContent.add(panelKartu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 24, -1, -1));

        panelKartu2.setBackground(new java.awt.Color(255, 255, 255));
        panelKartu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        panelKartu2.setPreferredSize(new java.awt.Dimension(210, 100));
        panelKartu2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Inter", 0, 22)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/check-solid (1).png")); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.setPreferredSize(new java.awt.Dimension(36, 36));
        panelKartu2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 14, -1, -1));

        jLabel12.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(130, 130, 130));
        jLabel12.setText("Peserta Lulus");
        jLabel12.setPreferredSize(new java.awt.Dimension(140, 16));
        panelKartu2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 14, -1, -1));

        lblPesertaLulus.setFont(new java.awt.Font("Inter", 1, 28)); // NOI18N
        lblPesertaLulus.setForeground(new java.awt.Color(0, 140, 60));
        lblPesertaLulus.setText("3");
        lblPesertaLulus.setPreferredSize(new java.awt.Dimension(100, 36));
        panelKartu2.add(lblPesertaLulus, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 34, -1, -1));

        jLabel18.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(170, 170, 170));
        jLabel18.setText("lulus seleksi");
        jLabel18.setPreferredSize(new java.awt.Dimension(140, 16));
        panelKartu2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 72, -1, -1));

        mainContent.add(panelKartu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 24, -1, -1));

        panelKartu3.setBackground(new java.awt.Color(255, 255, 255));
        panelKartu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        panelKartu3.setPreferredSize(new java.awt.Dimension(210, 100));
        panelKartu3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Inter", 1, 39)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("X");
        jLabel19.setPreferredSize(new java.awt.Dimension(36, 36));
        panelKartu3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 14, -1, -1));

        lblPesertaGugur.setFont(new java.awt.Font("Inter", 1, 28)); // NOI18N
        lblPesertaGugur.setForeground(new java.awt.Color(200, 0, 0));
        lblPesertaGugur.setText("0");
        lblPesertaGugur.setPreferredSize(new java.awt.Dimension(100, 36));
        panelKartu3.add(lblPesertaGugur, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 34, -1, -1));

        jLabel21.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(130, 130, 130));
        jLabel21.setText("Peserta Gugur");
        jLabel21.setPreferredSize(new java.awt.Dimension(140, 16));
        panelKartu3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 14, -1, -1));

        jLabel22.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(170, 170, 170));
        jLabel22.setText("gugur permanen");
        jLabel22.setPreferredSize(new java.awt.Dimension(140, 16));
        panelKartu3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 72, -1, -1));

        mainContent.add(panelKartu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 24, -1, -1));

        panelkartu4.setBackground(new java.awt.Color(255, 255, 255));
        panelkartu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        panelkartu4.setPreferredSize(new java.awt.Dimension(210, 100));
        panelkartu4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/profile (3) (1).png")); // NOI18N
        jLabel23.setToolTipText("");
        jLabel23.setPreferredSize(new java.awt.Dimension(36, 36));
        panelkartu4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel24.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(130, 130, 130));
        jLabel24.setText("Total Instruktur");
        jLabel24.setPreferredSize(new java.awt.Dimension(140, 16));
        panelkartu4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 14, -1, -1));

        lblTotalInstruktur.setFont(new java.awt.Font("Inter", 1, 28)); // NOI18N
        lblTotalInstruktur.setForeground(new java.awt.Color(0, 100, 100));
        lblTotalInstruktur.setText("5");
        lblTotalInstruktur.setPreferredSize(new java.awt.Dimension(100, 36));
        panelkartu4.add(lblTotalInstruktur, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 34, -1, -1));

        jLabel26.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(170, 170, 170));
        jLabel26.setText("instruktur aktif");
        jLabel26.setPreferredSize(new java.awt.Dimension(140, 16));
        panelkartu4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 72, -1, -1));

        mainContent.add(panelkartu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 24, -1, -1));

        jLabel27.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(25, 25, 25));
        jLabel27.setText("Daftar Peserta Terbaru");
        jLabel27.setPreferredSize(new java.awt.Dimension(280, 20));
        mainContent.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 148, -1, -1));

        jLabel28.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(150, 150, 150));
        jLabel28.setText("Menampilkan seluruh peserta yang terdaftar");
        jLabel28.setPreferredSize(new java.awt.Dimension(360, 16));
        mainContent.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 170, -1, -1));

        scrollPane1.setPreferredSize(new java.awt.Dimension(930, 380));

        tabelPeserta.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        tabelPeserta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "ID Peserta", "Nama Lengkap", "Level Bahasa", "Program", "Status Seleksi", "Status Bayar", "Status Keberangkatan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelPeserta.setGridColor(new java.awt.Color(235, 235, 235));
        tabelPeserta.setRowHeight(34);
        tabelPeserta.setSelectionBackground(new java.awt.Color(255, 230, 230));
        tabelPeserta.setSelectionForeground(new java.awt.Color(122, 0, 0));
        tabelPeserta.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(tabelPeserta);

        scrollPane1.add(jScrollPane1);

        mainContent.add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 196, -1, 230));

        btnTambahPeserta.setBackground(new java.awt.Color(122, 0, 0));
        btnTambahPeserta.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        btnTambahPeserta.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahPeserta.setText("Tambah Peserta");
        btnTambahPeserta.setBorderPainted(false);
        btnTambahPeserta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambahPeserta.setFocusPainted(false);
        btnTambahPeserta.setPreferredSize(new java.awt.Dimension(134, 32));
        btnTambahPeserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahPesertaActionPerformed(evt);
            }
        });
        mainContent.add(btnTambahPeserta, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 148, -1, -1));

        add(mainContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahPesertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPesertaActionPerformed
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
    
        if (parentWindow instanceof java.awt.Frame) {
            FormTambahPeserta tambah = new FormTambahPeserta((java.awt.Frame) parentWindow, true);
            tambah.setVisible(true);

            loadTableData(); 
        }
    }//GEN-LAST:event_btnTambahPesertaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambahPeserta;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPesertaGugur;
    private javax.swing.JLabel lblPesertaLulus;
    private javax.swing.JLabel lblTotalInstruktur;
    private javax.swing.JLabel lblTotalPeserta;
    private javax.swing.JPanel mainContent;
    private javax.swing.JPanel panelKartu1;
    private javax.swing.JPanel panelKartu2;
    private javax.swing.JPanel panelKartu3;
    private javax.swing.JPanel panelkartu4;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTable tabelPeserta;
    // End of variables declaration//GEN-END:variables
}
