/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

/**
 *
 * @author arelssi
 */
public class PanelLaporan extends javax.swing.JPanel {

    /**
     * Creates new form PanelLaporan
     */
    public PanelLaporan() {
        initComponents();
        setPreferredSize(new java.awt.Dimension(980, 616));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlToolbar = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        cbFilter = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbFilter1 = new javax.swing.JComboBox<>();
        panelTabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSeleksi = new javax.swing.JTable();
        lblTotalData = new javax.swing.JLabel();
        kartuTotal3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblTotalSeleksi1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        kartuTotal4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblTotalSeleksi2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kartuTotal5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblTotalSeleksi3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        kartuTotal6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblTotalSeleksi4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelPerProgram = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel19 = new javax.swing.JLabel();
        jProgressBar3 = new javax.swing.JProgressBar();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelPerProgram1 = new javax.swing.JPanel();
        jProgressBar4 = new javax.swing.JProgressBar();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jProgressBar5 = new javax.swing.JProgressBar();
        jLabel27 = new javax.swing.JLabel();
        jProgressBar6 = new javax.swing.JProgressBar();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlToolbar.setBackground(new java.awt.Color(255, 255, 255));
        pnlToolbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        pnlToolbar.setPreferredSize(new java.awt.Dimension(980, 56));
        pnlToolbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Reset");
        pnlToolbar.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 90, 34));

        cbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua" }));
        pnlToolbar.add(cbFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 130, 34));

        jButton3.setBackground(new java.awt.Color(0, 122, 0));
        jButton3.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Ekspor Laporan");
        pnlToolbar.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, 34));

        jLabel2.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("Program:");
        pnlToolbar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 30, 30));
        jLabel4.setText("Periode: ");
        pnlToolbar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 30, -1, -1));

        cbFilter1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua" }));
        pnlToolbar.add(cbFilter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 140, 34));

        add(pnlToolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        panelTabel.setBackground(new java.awt.Color(255, 255, 255));
        panelTabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        panelTabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelSeleksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID", "Nama Peserta", "Program", "Nilai", "No. Paspor", "tgl_berangkat", "Status"
            }
        ));
        jScrollPane1.setViewportView(tabelSeleksi);
        if (tabelSeleksi.getColumnModel().getColumnCount() > 0) {
            tabelSeleksi.getColumnModel().getColumn(0).setMaxWidth(50);
            tabelSeleksi.getColumnModel().getColumn(4).setMaxWidth(70);
        }

        panelTabel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 37, 910, 332));

        lblTotalData.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        lblTotalData.setForeground(new java.awt.Color(120, 120, 120));
        lblTotalData.setText("Rekap Keberangkatan Peserta");
        panelTabel.add(lblTotalData, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 10, -1, -1));

        add(panelTabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 910, 190));

        kartuTotal3.setBackground(new java.awt.Color(255, 255, 255));
        kartuTotal3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        kartuTotal3.setPreferredSize(new java.awt.Dimension(296, 56));
        kartuTotal3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(130, 130, 130));
        jLabel7.setText("dari seluruh seleksi");
        kartuTotal3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblTotalSeleksi1.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        lblTotalSeleksi1.setForeground(new java.awt.Color(255, 165, 0));
        lblTotalSeleksi1.setText("0");
        kartuTotal3.add(lblTotalSeleksi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 235, 235));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/star.png")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 40));
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 40, -1));

        kartuTotal3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 40, 40));

        jLabel9.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(130, 130, 130));
        jLabel9.setText("Rata-rata Nilai");
        kartuTotal3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        add(kartuTotal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 217, 120));

        kartuTotal4.setBackground(new java.awt.Color(255, 255, 255));
        kartuTotal4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        kartuTotal4.setPreferredSize(new java.awt.Dimension(300, 56));
        kartuTotal4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(130, 130, 130));
        jLabel8.setText("Peserta Terdaftar");
        kartuTotal4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblTotalSeleksi2.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        lblTotalSeleksi2.setForeground(new java.awt.Color(122, 0, 0));
        lblTotalSeleksi2.setText("0");
        kartuTotal4.add(lblTotalSeleksi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 235, 235));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/user.png")); // NOI18N
        jLabel3.setText("i");
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 40));
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 0, 30, 40));

        kartuTotal4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 40, 40));

        jLabel10.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(130, 130, 130));
        jLabel10.setText("Total Peserta");
        kartuTotal4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        add(kartuTotal4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 217, 120));

        kartuTotal5.setBackground(new java.awt.Color(255, 255, 255));
        kartuTotal5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        kartuTotal5.setPreferredSize(new java.awt.Dimension(300, 56));
        kartuTotal5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(130, 130, 130));
        jLabel11.setText("4 dari 6 peserta lulus");
        kartuTotal5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblTotalSeleksi3.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        lblTotalSeleksi3.setForeground(new java.awt.Color(0, 122, 0));
        lblTotalSeleksi3.setText("0 %");
        kartuTotal5.add(lblTotalSeleksi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 235, 235));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/check.png")); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(60, 40));
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 40, -1));

        kartuTotal5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 40, 40));

        jLabel12.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(130, 130, 130));
        jLabel12.setText("Tingkat Kelulusan");
        kartuTotal5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        add(kartuTotal5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 217, 120));

        kartuTotal6.setBackground(new java.awt.Color(255, 255, 255));
        kartuTotal6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        kartuTotal6.setPreferredSize(new java.awt.Dimension(296, 56));
        kartuTotal6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(130, 130, 130));
        jLabel13.setText("dokumen lengkap");
        kartuTotal6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblTotalSeleksi4.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        lblTotalSeleksi4.setForeground(new java.awt.Color(0, 0, 122));
        lblTotalSeleksi4.setText("0");
        kartuTotal6.add(lblTotalSeleksi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 235, 235));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon("/home/arelssi/Downloads/airplane (1).png")); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(60, 40));
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 40, -1));

        kartuTotal6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 40, 40));

        jLabel14.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(130, 130, 130));
        jLabel14.setText("Siap Berangkat");
        kartuTotal6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        add(kartuTotal6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 217, 120));

        panelPerProgram.setBackground(new java.awt.Color(255, 255, 255));
        panelPerProgram.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        panelPerProgram.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setForeground(new java.awt.Color(0, 0, 122));
        jProgressBar1.setValue(30);
        panelPerProgram.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 10));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(110, 110, 110));
        jLabel15.setText("Rekap status seluruh peserta lulus ");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 20, -1, -1));

        jLabel16.setFont(new java.awt.Font("Inter", 1, 9)); // NOI18N
        jLabel16.setText("Status Keberangkatan");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 7, -1, -1));

        panelPerProgram.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 447, 40));

        jLabel17.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(30, 30, 30));
        jLabel17.setText("2");
        panelPerProgram.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 57, -1, -1));

        jLabel18.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(30, 30, 30));
        jLabel18.setText("Menunggu Dokumen");
        panelPerProgram.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jProgressBar2.setForeground(new java.awt.Color(222, 122, 0));
        jProgressBar2.setValue(40);
        panelPerProgram.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, 10));

        jLabel19.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(30, 30, 30));
        jLabel19.setText("Belum Berangkat");
        panelPerProgram.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jProgressBar3.setForeground(new java.awt.Color(100, 100, 100));
        jProgressBar3.setValue(10);
        panelPerProgram.add(jProgressBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, 10));

        jLabel20.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(30, 30, 30));
        jLabel20.setText("Siap Berangkat");
        panelPerProgram.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel21.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(30, 30, 30));
        jLabel21.setText("4");
        panelPerProgram.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 77, 10, -1));

        jLabel22.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(30, 30, 30));
        jLabel22.setText("1");
        panelPerProgram.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        add(panelPerProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 447, 150));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        panelPerProgram1.setBackground(new java.awt.Color(255, 255, 255));
        panelPerProgram1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        panelPerProgram1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar4.setForeground(new java.awt.Color(122, 0, 0));
        jProgressBar4.setValue(20);
        panelPerProgram1.add(jProgressBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 10));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(110, 110, 110));
        jLabel23.setText("Distribusi peserta berdasarkan program");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 20, -1, -1));

        jLabel24.setFont(new java.awt.Font("Inter", 1, 9)); // NOI18N
        jLabel24.setText("Peserta Per program");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 7, -1, -1));

        panelPerProgram1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 447, 40));

        jLabel25.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(30, 30, 30));
        jLabel25.setText("2");
        panelPerProgram1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 57, -1, -1));

        jLabel26.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(30, 30, 30));
        jLabel26.setText("Penginapan");
        panelPerProgram1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jProgressBar5.setForeground(new java.awt.Color(122, 0, 0));
        jProgressBar5.setValue(70);
        panelPerProgram1.add(jProgressBar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, 10));

        jLabel27.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(30, 30, 30));
        jLabel27.setText("Industri Makanan");
        panelPerProgram1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jProgressBar6.setForeground(new java.awt.Color(122, 0, 0));
        jProgressBar6.setValue(70);
        panelPerProgram1.add(jProgressBar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, 10));

        jLabel28.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(30, 30, 30));
        jLabel28.setText("Industri Mesin");
        panelPerProgram1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel29.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(30, 30, 30));
        jLabel29.setText("7");
        panelPerProgram1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 77, 10, -1));

        jLabel30.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(30, 30, 30));
        jLabel30.setText("7");
        panelPerProgram1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        add(panelPerProgram1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 447, 150));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbFilter;
    private javax.swing.JComboBox<String> cbFilter1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JProgressBar jProgressBar6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel kartuTotal3;
    private javax.swing.JPanel kartuTotal4;
    private javax.swing.JPanel kartuTotal5;
    private javax.swing.JPanel kartuTotal6;
    private javax.swing.JLabel lblTotalData;
    private javax.swing.JLabel lblTotalSeleksi1;
    private javax.swing.JLabel lblTotalSeleksi2;
    private javax.swing.JLabel lblTotalSeleksi3;
    private javax.swing.JLabel lblTotalSeleksi4;
    private javax.swing.JPanel panelPerProgram;
    private javax.swing.JPanel panelPerProgram1;
    private javax.swing.JPanel panelTabel;
    private javax.swing.JPanel pnlToolbar;
    private javax.swing.JTable tabelSeleksi;
    // End of variables declaration//GEN-END:variables
}
