/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.instruktur;

/**
 *
 * @author arelssi
 */
public class CardJadwal extends javax.swing.JPanel {

    /**
     * Creates new form CardJadwal
     */
    public CardJadwal() {
        initComponents();
        this.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, this.getPreferredSize().height));
    }
    
    public void setJadwalData(String jam, String hari, String bab, String kelas, String status) {
        lblJam3.setText(jam);
        lblHari3.setText(hari);
        lblBab.setText(bab);
        lblKelas.setText(kelas);
        btnStatus.setText(status);

        // Atur warna tombol berdasarkan status
        if (status.equalsIgnoreCase("Selesai")) {
            btnStatus.setBackground(new java.awt.Color(100, 255, 100)); // Hijau
            btnStatus.setForeground(java.awt.Color.BLACK);
        } else {
            btnStatus.setBackground(new java.awt.Color(255, 102, 102)); // Merah muda "Hari ini"
            btnStatus.setForeground(java.awt.Color.WHITE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        lblJam3 = new javax.swing.JLabel();
        lblHari3 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        lblKelas = new javax.swing.JLabel();
        lblBab = new javax.swing.JLabel();
        btnStatus = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(240, 240, 240));
        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jPanel14.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJam3.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        lblJam3.setText("08 : 00");
        jPanel14.add(lblJam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblHari3.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        lblHari3.setForeground(new java.awt.Color(100, 100, 100));
        lblHari3.setText("Senin");
        jPanel14.add(lblHari3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jPanel15.setBackground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 10, 10));

        lblKelas.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        lblKelas.setText("Kelas A  - 120");
        jPanel14.add(lblKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        lblBab.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        lblBab.setText("Minna No Nihonggo Bab 1");
        jPanel14.add(lblBab, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        btnStatus.setText("Selesai");
        btnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusActionPerformed(evt);
            }
        });
        jPanel14.add(btnStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jPanel13.add(jPanel14);

        add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStatus;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblBab;
    private javax.swing.JLabel lblHari;
    private javax.swing.JLabel lblHari1;
    private javax.swing.JLabel lblHari3;
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lblJam1;
    private javax.swing.JLabel lblJam3;
    private javax.swing.JLabel lblKelas;
    // End of variables declaration//GEN-END:variables
}
