/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.instruktur;

import DataStore.DataStore;
import Model.Instruktur;
import Model.Jadwal;
import Model.Pengguna;
import Util.TabelUtil;
import Util.TombolAksiEditor;
import Util.TombolAksiRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arelssi
 */
public class PanelJadwalKelas extends javax.swing.JPanel {

    /**
     * Creates new form PanelJadwalKelas
     */
    private String idInstrukturAktif;
    private int mingguAktif = 0;
    
    public PanelJadwalKelas(String idInstruktur) {
        initComponents();
        
        this.idInstrukturAktif = idInstruktur;
        
        setupTable();
        loadTableData();
    }
    
    private void setupTable() {
        tabelJadwal.setRowHeight(40);
        TabelUtil.autoResizeKolom(tabelJadwal);
        javax.swing.table.JTableHeader header = tabelJadwal.getTableHeader();
        
        header.setBackground(new java.awt.Color(122, 0, 0));
        header.setForeground(java.awt.Color.WHITE);
        
        header.setFont(new java.awt.Font("Inter", java.awt.Font.BOLD, 13)); 
        header.setOpaque(true);
    }
    
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) tabelJadwal.getModel();
        model.setRowCount(0); // Kosongkan tabel sebelum diisi ulang
        
        // 1. LOGIKA ANTI-ERROR (Mencari ID Instruktur Asli)
        String idAsli = this.idInstrukturAktif;
        for (Pengguna pgn : DataStore.daftarPengguna) {
            if (pgn instanceof Instruktur) {
                Instruktur ins = (Instruktur) pgn;
                if ((ins.getIdInstruktur() != null && ins.getIdInstruktur().equals(idInstrukturAktif)) || 
                    (ins.getUsername() != null && ins.getUsername().equals(idInstrukturAktif))) {
                    idAsli = ins.getIdInstruktur(); // Dapatkan ID aslinya (misal: INS001)
                    break;
                }
            }
        }

        int no = 1;

        // 2. LOOPING DATA JADWAL
        for (Jadwal j : DataStore.daftarJadwal) {
            if (j.getIdInstruktur().equals(idAsli)) {
                model.addRow(new Object[]{
                    no++,
                    j.getJamMulai(),
                    j.getHari(),
                    j.getNamaMateri(),
                    "Kelas " + j.getNamaKelas(),
                    j.getDurasi() + " Menit",
                    j.getStatusJadwal(),
                    ""
                });
            }
        }
    }
    
    private void updateNavigasiMinggu() {
        // Anggap minggu ini adalah Minggu ke-20 (Sesuai desain)
        int mingguKe = 20 + mingguAktif;
        lblMingguKe.setText("Minggu ke-" + mingguKe);

        // Ubah teks ComboBox dan Label Tanggal (Dummy) tanpa memicu event ComboBox dua kali
        cbMinggu.removeActionListener(cbMinggu.getActionListeners()[0]); // Matikan sementara

        if (mingguAktif == 0) {
            cbMinggu.setSelectedItem("Minggu ini");
            lblTanggalBanner.setText("12 - 16 Mei");
        } else if (mingguAktif == 1) {
            cbMinggu.setSelectedItem("Minggu depan");
            lblTanggalBanner.setText("19 - 23 Mei");
        } else if (mingguAktif == -1) {
            cbMinggu.setSelectedItem("Minggu lalu");
            lblTanggalBanner.setText("5 - 9 Mei");
        } else {
            // Jika diklik Next/Prev melebihi jangkauan dropdown
            cbMinggu.setSelectedItem("Pilih Minggu"); 
            lblTanggalBanner.setText("Rentang Tanggal Lain");
        }
        
        cbMinggu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMingguActionPerformed(evt);
            }
        });

        // Terakhir: Panggil ulang data tabel (Agar isi tabel ikut menyesuaikan)
        loadTableData(); 
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTabel = new javax.swing.JPanel();
        scrollTabel = new javax.swing.JScrollPane();
        tabelJadwal = new javax.swing.JTable();
        lblTotalData = new javax.swing.JLabel();
        panelKartu1 = new javax.swing.JPanel();
        lblTanggalBanner = new javax.swing.JLabel();
        lblMingguKe = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        cbMinggu = new javax.swing.JComboBox<>();
        btnPrev = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTabel.setBackground(new java.awt.Color(255, 255, 255));
        panelTabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        panelTabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollTabel.setPreferredSize(new java.awt.Dimension(948, 460));

        tabelJadwal.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        tabelJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Jam", "Hari", "Materi", "Kelas", "Durasi", "Status Jadwal", "Aksi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelJadwal.setRowHeight(36);
        tabelJadwal.setSelectionBackground(new java.awt.Color(255, 230, 230));
        tabelJadwal.setSelectionForeground(new java.awt.Color(122, 0, 0));
        tabelJadwal.setShowHorizontalLines(true);
        scrollTabel.setViewportView(tabelJadwal);

        panelTabel.add(scrollTabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(panelTabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 370));

        lblTotalData.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        lblTotalData.setForeground(new java.awt.Color(120, 120, 120));
        lblTotalData.setText("Detail Jadwal Minggu Ini");
        lblTotalData.setPreferredSize(new java.awt.Dimension(300, 20));
        add(lblTotalData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        panelKartu1.setBackground(new java.awt.Color(122, 0, 0));
        panelKartu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        panelKartu1.setPreferredSize(new java.awt.Dimension(210, 100));
        panelKartu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTanggalBanner.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        lblTanggalBanner.setForeground(new java.awt.Color(255, 255, 255));
        lblTanggalBanner.setText("12 - 16 Mei");
        lblTanggalBanner.setPreferredSize(new java.awt.Dimension(100, 36));
        panelKartu1.add(lblTanggalBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 230, -1));

        lblMingguKe.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        lblMingguKe.setForeground(new java.awt.Color(240, 170, 170));
        lblMingguKe.setText("Minggu ke-20");
        lblMingguKe.setPreferredSize(new java.awt.Dimension(140, 16));
        panelKartu1.add(lblMingguKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 45, 260, -1));

        btnNext.setBackground(new java.awt.Color(255, 200, 200));
        btnNext.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(122, 0, 0));
        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        panelKartu1.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 50, 40));

        cbMinggu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minggu Ini", "Minggu Depan", "Minggu Lalu" }));
        cbMinggu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMingguActionPerformed(evt);
            }
        });
        panelKartu1.add(cbMinggu, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 120, 40));

        btnPrev.setBackground(new java.awt.Color(255, 200, 200));
        btnPrev.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(122, 0, 0));
        btnPrev.setText("<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        panelKartu1.add(btnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 40));

        add(panelKartu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 950, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        mingguAktif++; 
        updateNavigasiMinggu(); 
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        mingguAktif--;
        updateNavigasiMinggu();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void cbMingguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMingguActionPerformed
        if (cbMinggu.getSelectedItem() != null) {
            String pilihan = cbMinggu.getSelectedItem().toString();
            
            if (pilihan.equals("Minggu Ini")) {
                mingguAktif = 0;
            } else if (pilihan.equals("Minggu Depan")) {
                mingguAktif = 1;
            } else if (pilihan.equals("Minggu Lalu")) {
                mingguAktif = -1;
            }
            
            // Panggil pembaruan layar kecuali combobox itu sendiri
            updateNavigasiMinggu();
        }
    }//GEN-LAST:event_cbMingguActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JComboBox<String> cbMinggu;
    private javax.swing.JLabel lblMingguKe;
    private javax.swing.JLabel lblTanggalBanner;
    private javax.swing.JLabel lblTotalData;
    private javax.swing.JPanel panelKartu1;
    private javax.swing.JPanel panelTabel;
    private javax.swing.JScrollPane scrollTabel;
    private javax.swing.JTable tabelJadwal;
    // End of variables declaration//GEN-END:variables
}
